import puppeteer from "puppeteer"
import fs from "fs/promises"
//import * as players from "./appfolder/playerodds.json" with { type : "json"}
import * as games from "./appfolder/games.json" with { type : "json"}
import { setName, setNameComplete } from "./setNames.js"


export async function getPlayersFromOdds(date){
    const playerLocal = Object.values(players)
    const playerLocalB = Object.values(playerLocal[0])
    let onePlayer = []
    // playerLocalB.length
    for(let i = 0 ; i < playerLocalB.length ; i++){
        let replaceName = playerLocalB[i].finalName.replace(" ", "-")
        if (!onePlayer.includes(replaceName)){
            onePlayer.push(replaceName)
        }
    }
    const onePlayerTeam = await statsLastFive(onePlayer,date)
    const playersComplete = await searchTeamName(onePlayerTeam)
    const gameComplete = await searchRivalTeamName(playersComplete)
    await statsLastFiveVersus(gameComplete, date)
}

async function statsLastFive(onePlayer,date){
    let onePlayerStats = []
    let onePlayerTeam = []
    let teams = []
    //onePlayer.length
    for(let i = 0 ; i < onePlayer.length ; i++){
        if( onePlayer[i] !== undefined ){
            const player =    await getDataFromWeb(onePlayer[i])
            const newNamePlayer = setNameComplete(player)
            const newName =setName(player.name)
            player.name = newName
            onePlayerStats.push(newNamePlayer)
            const playerTeam = { name: newName, team:player.team.replace("2024-25 ","")}
            onePlayerTeam.push(playerTeam)
            if (!teams.includes(player.team)){
                teams.push(player.team)
            }
        }
    }
    if(date !== undefined){
        await fs.writeFile("appfolder/playerTeams.json", JSON.stringify(onePlayerTeam))
        
        const playersStats = "folder/" + date + "/lastFive.json"
        await fs.writeFile(playersStats, JSON.stringify(onePlayerStats))
        await fs.writeFile("appfolder/playerStats.json", JSON.stringify(onePlayerStats))
        console.log("stats de ultimos 5 juegos guardados")
    }
    return onePlayerTeam
}

async function statsLastFiveVersus(gameComplete, date){
    const onePlayerStats = []
    for(let i = 0 ; i < gameComplete.length ; i++){
        if( gameComplete[i] !== undefined ){
              const player =    await getDataFromWebVs(gameComplete[i].name.replace(" ","-"), gameComplete[i].rival)
              const newNamePlayer = setNameComplete(player)
            onePlayerStats.push(newNamePlayer)
        }
    }
   const playersStats = "folder/" + date + "/lastFiveVs.json"
   await fs.writeFile(playersStats, JSON.stringify(onePlayerStats))
   await fs.writeFile("appfolder/playerStatsvs.json", JSON.stringify(onePlayerStats))
   console.log("stats de ultimos 5 juegos guardados contra")

}
async function getDataFromWeb(name){
    const browser = await puppeteer.launch({
    headless:false,
    //slowMo: 500
    })
    const page = await browser.newPage()
    let url = ""
    if(name==="Nicolas-Claxton"){
        url = "https://www.statmuse.com/nba/ask/nic-claxton-last-5-games"
    } else if (name==="Cameron-Thomas"){
        url = "https://www.statmuse.com/nba/ask/cam-thomas-last-5-games"
    } else {
        url = "https://www.statmuse.com/nba/ask/"+name+"-last-5-games"
    }
    await page.goto(url)
    const result = await page.evaluate(()=> {
        const atributte = "body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > "


            const name = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td.text-left.px-2.py-2\\.5.sticky.left-0.bg-gray-8.dark\\:bg-gray-3 > a > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td.text-left.px-2.py-2\\.5.sticky.left-0.bg-gray-8.dark\\:bg-gray-3 > a > div > span").innerText : "sin data"
            const team = document.querySelector(atributte + "tr:nth-child(5) > td:nth-child(5) > a").getAttribute('title') === null 
                            ? "sin data" 
                            : document.querySelector(atributte + "tr:nth-child(5) > td:nth-child(5) > a").getAttribute('title')
            const date1 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td:nth-child(4) > a > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td:nth-child(4) > a > div > span").innerText: "sin data"
            const min1 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td:nth-child(8) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td:nth-child(8) > span > div > span").innerText: "sin data"
            const pts1 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td:nth-child(9) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td:nth-child(9) > span > div > span").innerText: "sin data"
            const reb1 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td:nth-child(10) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td:nth-child(10) > span > div > span").innerText: "sin data"
            const ast1 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td:nth-child(11) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td:nth-child(11) > span > div > span").innerText: "sin data"
            const triples1 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td:nth-child(17) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td:nth-child(17) > span > div > span").innerText: "sin data"
            const triplesAttemps1 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td:nth-child(18) > span > div > span")  !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td:nth-child(18) > span > div > span").innerText: "sin data"
 
                const date2 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(2) > td:nth-child(4) > a > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(2) > td:nth-child(4) > a > div > span").innerText: "sin data"
                const min2 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(2) > td:nth-child(8) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(2) > td:nth-child(8) > span > div > span").innerText: "sin data"
                const pts2 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(2) > td:nth-child(9) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(2) > td:nth-child(9) > span > div > span").innerText: "sin data"
                const reb2 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(2) > td:nth-child(10) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(2) > td:nth-child(10) > span > div > span").innerText: "sin data"
                const ast2 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(2) > td:nth-child(11) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(2) > td:nth-child(11) > span > div > span").innerText: "sin data"
                const triples2 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(2) > td:nth-child(17) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(2) > td:nth-child(17) > span > div > span").innerText: "sin data"
                const triplesAttemps2 =  document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(2) > td:nth-child(18) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(2) > td:nth-child(18) > span > div > span").innerText: "sin data"

                    const date3 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(3) > td:nth-child(4) > a > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(3) > td:nth-child(4) > a > div > span").innerText: "sin data"
                    const min3 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(3) > td:nth-child(8) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(3) > td:nth-child(8) > span > div > span").innerText: "sin data"
                    const pts3 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(3) > td:nth-child(9) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(3) > td:nth-child(9) > span > div > span").innerText: "sin data"
                    const reb3 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(3) > td:nth-child(10) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(3) > td:nth-child(10) > span > div > span").innerText: "sin data"
                    const ast3 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(3) > td:nth-child(11) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(3) > td:nth-child(11) > span > div > span").innerText: "sin data"
                    const triples3 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(3) > td:nth-child(17) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(3) > td:nth-child(17) > span > div > span").innerText: "sin data"
                    const triplesAttemps3 =  document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(3) > td:nth-child(18) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(3) > td:nth-child(18) > span > div > span").innerText: "sin data"

                        const date4 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(4) > td:nth-child(4) > a > div > span") !== null ?  document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(4) > td:nth-child(4) > a > div > span").innerText: "sin data"
                        const min4 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(4) > td:nth-child(8) > span > div > span") !== null ?  document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(4) > td:nth-child(8) > span > div > span").innerText: "sin data"
                        const pts4 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(4) > td:nth-child(9) > span > div > span") !== null ?  document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(4) > td:nth-child(9) > span > div > span").innerText: "sin data"
                        const reb4 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(4) > td:nth-child(10) > span > div > span") !== null ?  document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(4) > td:nth-child(10) > span > div > span").innerText: "sin data"
                        const ast4 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(4) > td:nth-child(11) > span > div > span") !== null ?  document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(4) > td:nth-child(11) > span > div > span").innerText: "sin data"
                        const triples4 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(4) > td:nth-child(17) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(4) > td:nth-child(17) > span > div > span").innerText: "sin data"
                        const triplesAttemps4 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(4) > td:nth-child(18) > span > div > span")  !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(4) > td:nth-child(18) > span > div > span").innerText: "sin data"
                        

                        

                            const date5 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(5) > td:nth-child(4) > a > div > span") !== null ?  document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(5) > td:nth-child(4) > a > div > span").innerText: "sin data"
                            const min5 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(5) > td:nth-child(8) > span > div > span") !== null ?  document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(5) > td:nth-child(8) > span > div > span").innerText: "sin data"
                            const pts5 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(5) > td:nth-child(9) > span > div > span") !== null ?  document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(5) > td:nth-child(9) > span > div > span").innerText: "sin data"
                            const reb5 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(5) > td:nth-child(10) > span > div > span") !== null ?  document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(5) > td:nth-child(10) > span > div > span").innerText: "sin data"
                            const ast5 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(5) > td:nth-child(11) > span > div > span") !== null ?  document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(5) > td:nth-child(11) > span > div > span").innerText: "sin data"
                            const triples5 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(5) > td:nth-child(17) > span > div > span") !== null ?  document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(5) > td:nth-child(17) > span > div > span").innerText: "sin data"
                            const triplesAttemps5 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(5) > td:nth-child(18) > span > div > span") !== null ?   document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(5) > td:nth-child(18) > span > div > span").innerText: "sin data"
                            return  { name, team, stats : {
                                game1:{"date":date1, "min":min1, "pts":pts1, "reb": reb1, "ast": ast1, "tpm": triples1, "tpa":triplesAttemps1,},
                                game2:{"date":date2, "min":min2, "pts":pts2, "reb": reb2, "ast": ast2, "tpm": triples2, "tpa":triplesAttemps2,},
                                game3:{"date":date3, "min":min3, "pts":pts3, "reb": reb3, "ast": ast3, "tpm": triples3, "tpa":triplesAttemps3,},
                                game4:{"date":date4, "min":min4, "pts":pts4, "reb": reb4, "ast": ast4, "tpm": triples4, "tpa":triplesAttemps4,},
                                game5:{"date":date5, "min":min5, "pts":pts5, "reb": reb5, "ast": ast5, "tpm": triples5, "tpa":triplesAttemps5,},}
                            }
                            
                        
    })

    await browser.close()
    return result
}

async function getDataFromWebVs(name, rival){
    const browser = await puppeteer.launch({
    headless:false,
    //slowMo: 500
    })
    const page = await browser.newPage()
    const url = "https://www.statmuse.com/nba/ask/"+name+"-last-5-games-vs-" + rival
    await page.goto(url)
    const result = await page.evaluate(()=> {
        if(document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1)") !==null){
            const name = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td.text-left.px-2.py-2\\.5.sticky.left-0.bg-gray-8.dark\\:bg-gray-3 > a > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td.text-left.px-2.py-2\\.5.sticky.left-0.bg-gray-8.dark\\:bg-gray-3 > a > div > span").innerText : "sin data"
            const date1 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td:nth-child(4) > a > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td:nth-child(4) > a > div > span").innerText: "sin data"
            const min1 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td:nth-child(8) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td:nth-child(8) > span > div > span").innerText: "sin data"
            const pts1 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td:nth-child(9) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td:nth-child(9) > span > div > span").innerText: "sin data"
            const reb1 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td:nth-child(10) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td:nth-child(10) > span > div > span").innerText: "sin data"
            const ast1 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td:nth-child(11) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td:nth-child(11) > span > div > span").innerText: "sin data"
            const triples1 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td:nth-child(17) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td:nth-child(17) > span > div > span").innerText: "sin data"
            const triplesAttemps1 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td:nth-child(18) > span > div > span")  !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(1) > td:nth-child(18) > span > div > span").innerText: "sin data"
            if(document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(2)") !==null){
                const date2 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(2) > td:nth-child(4) > a > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(2) > td:nth-child(4) > a > div > span").innerText: "sin data"
                const min2 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(2) > td:nth-child(8) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(2) > td:nth-child(8) > span > div > span").innerText: "sin data"
                const pts2 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(2) > td:nth-child(9) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(2) > td:nth-child(9) > span > div > span").innerText: "sin data"
                const reb2 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(2) > td:nth-child(10) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(2) > td:nth-child(10) > span > div > span").innerText: "sin data"
                const ast2 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(2) > td:nth-child(11) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(2) > td:nth-child(11) > span > div > span").innerText: "sin data"
                const triples2 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(2) > td:nth-child(17) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(2) > td:nth-child(17) > span > div > span").innerText: "sin data"
                const triplesAttemps2 =  document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(2) > td:nth-child(18) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(2) > td:nth-child(18) > span > div > span").innerText: "sin data"
                if(document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(3)") !==null){
                    const date3 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(3) > td:nth-child(4) > a > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(3) > td:nth-child(4) > a > div > span").innerText: "sin data"
                    const min3 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(3) > td:nth-child(8) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(3) > td:nth-child(8) > span > div > span").innerText: "sin data"
                    const pts3 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(3) > td:nth-child(9) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(3) > td:nth-child(9) > span > div > span").innerText: "sin data"
                    const reb3 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(3) > td:nth-child(10) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(3) > td:nth-child(10) > span > div > span").innerText: "sin data"
                    const ast3 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(3) > td:nth-child(11) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(3) > td:nth-child(11) > span > div > span").innerText: "sin data"
                    const triples3 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(3) > td:nth-child(17) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(3) > td:nth-child(17) > span > div > span").innerText: "sin data"
                    const triplesAttemps3 =  document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(3) > td:nth-child(18) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(3) > td:nth-child(18) > span > div > span").innerText: "sin data"
                    if(document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(4)") !==null){
                        const date4 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(4) > td:nth-child(4) > a > div > span") !== null ?  document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(4) > td:nth-child(4) > a > div > span").innerText: "sin data"
                        const min4 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(4) > td:nth-child(8) > span > div > span") !== null ?  document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(4) > td:nth-child(8) > span > div > span").innerText: "sin data"
                        const pts4 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(4) > td:nth-child(9) > span > div > span") !== null ?  document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(4) > td:nth-child(9) > span > div > span").innerText: "sin data"
                        const reb4 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(4) > td:nth-child(10) > span > div > span") !== null ?  document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(4) > td:nth-child(10) > span > div > span").innerText: "sin data"
                        const ast4 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(4) > td:nth-child(11) > span > div > span") !== null ?  document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(4) > td:nth-child(11) > span > div > span").innerText: "sin data"
                        const triples4 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(4) > td:nth-child(17) > span > div > span") !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(4) > td:nth-child(17) > span > div > span").innerText: "sin data"
                        const triplesAttemps4 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(4) > td:nth-child(18) > span > div > span")  !== null ? document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(4) > td:nth-child(18) > span > div > span").innerText: "sin data"
                        if(document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(5)") !==null){
                            const date5 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(5) > td:nth-child(4) > a > div > span") !== null ?  document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(5) > td:nth-child(4) > a > div > span").innerText: "sin data"
                            const min5 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(5) > td:nth-child(8) > span > div > span") !== null ?  document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(5) > td:nth-child(8) > span > div > span").innerText: "sin data"
                            const pts5 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(5) > td:nth-child(9) > span > div > span") !== null ?  document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(5) > td:nth-child(9) > span > div > span").innerText: "sin data"
                            const reb5 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(5) > td:nth-child(10) > span > div > span") !== null ?  document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(5) > td:nth-child(10) > span > div > span").innerText: "sin data"
                            const ast5 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(5) > td:nth-child(11) > span > div > span") !== null ?  document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(5) > td:nth-child(11) > span > div > span").innerText: "sin data"
                            const triples5 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(5) > td:nth-child(17) > span > div > span") !== null ?  document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(5) > td:nth-child(17) > span > div > span").innerText: "sin data"
                            const triplesAttemps5 = document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(5) > td:nth-child(18) > span > div > span") !== null ?   document.querySelector("body > div.grid.grid-rows-1.gap-3.\\[--top-spacing\\:62px\\].flex-1.md\\:grid-cols-\\[1fr_300px\\].xl\\:grid-cols-\\[auto_1fr_300px\\] > div.min-w-0.h-full > div.content.flex.flex-col.gap-3 > div:nth-child(2) > div.flex-1.overflow-x-auto > astro-island > div > div > table > tbody > tr:nth-child(5) > td:nth-child(18) > span > div > span").innerText: "sin data"
                            return  { name,  stats : {
                                game1:{"date":date1, "min":min1, "pts":pts1, "reb": reb1, "ast": ast1, "tpm": triples1, "tpa":triplesAttemps1,},
                                game2:{"date":date2, "min":min2, "pts":pts2, "reb": reb2, "ast": ast2, "tpm": triples2, "tpa":triplesAttemps2,},
                                game3:{"date":date3, "min":min3, "pts":pts3, "reb": reb3, "ast": ast3, "tpm": triples3, "tpa":triplesAttemps3,},
                                game4:{"date":date4, "min":min4, "pts":pts4, "reb": reb4, "ast": ast4, "tpm": triples4, "tpa":triplesAttemps4,},
                                game5:{"date":date5, "min":min5, "pts":pts5, "reb": reb5, "ast": ast5, "tpm": triples5, "tpa":triplesAttemps5,},}
                            }
                            
                        }
                        return  { name,  stats : {
                            game1:{"date":date1, "min":min1, "pts":pts1, "reb": reb1, "ast": ast1, "tpm": triples1, "tpa":triplesAttemps1,},
                            game2:{"date":date2, "min":min2, "pts":pts2, "reb": reb2, "ast": ast2, "tpm": triples2, "tpa":triplesAttemps2,},
                            game3:{"date":date3, "min":min3, "pts":pts3, "reb": reb3, "ast": ast3, "tpm": triples3, "tpa":triplesAttemps3,},
                            game4:{"date":date4, "min":min4, "pts":pts4, "reb": reb4, "ast": ast4, "tpm": triples4, "tpa":triplesAttemps4,},
                            }
                        }
                    }
                    return  { name,  stats : {
                            game1:{"date":date1, "min":min1, "pts":pts1, "reb": reb1, "ast": ast1, "tpm": triples1, "tpa":triplesAttemps1,},
                            game2:{"date":date2, "min":min2, "pts":pts2, "reb": reb2, "ast": ast2, "tpm": triples2, "tpa":triplesAttemps2,},
                            game3:{"date":date3, "min":min3, "pts":pts3, "reb": reb3, "ast": ast3, "tpm": triples3, "tpa":triplesAttemps3,},
                            }
                        }
                }
                return  { name,  stats : {
                    game1:{"date":date1, "min":min1, "pts":pts1, "reb": reb1, "ast": ast1, "tpm": triples1, "tpa":triplesAttemps1,},
                    game2:{"date":date2, "min":min2, "pts":pts2, "reb": reb2, "ast": ast2, "tpm": triples2, "tpa":triplesAttemps2,},
                    }
                }
            }   
            return  { name,  stats : {
                game1:{"date":date1, "min":min1, "pts":pts1, "reb": reb1, "ast": ast1, "tpm": triples1, "tpa":triplesAttemps1,},
                }
            }
        }
    })

    await browser.close()
    return result
}
async function searchTeamName(onePlayer){
    const playersComplete = []
    const games = [
    {"gameName":"Celtics",      "statsName": "Boston Celtics"},
    {"gameName":"Nets",         "statsName": "Brooklyn Nets"},
    {"gameName":"Knicks",       "statsName": "New York Knicks"},
    {"gameName":"76ers",        "statsName": "Philadelphia 76ers"},
    {"gameName":"Raptors",      "statsName": "Toronto Raptors"},
    {"gameName":"Warriors",     "statsName": "Golden State Warriors"},
    {"gameName":"Clippers",     "statsName": "L.A. Clippers"},
    {"gameName":"Lakers",       "statsName": "Los Angeles Lakers"},   
    {"gameName":"Suns",         "statsName": "Phoenix Suns"},
    {"gameName":"kings",        "statsName": "Sacramento Kings"},
    {"gameName":"Cavaliers",    "statsName": "Cleveland Cavaliers"},
    {"gameName":"Bulls",        "statsName": "Chicago Bulls"},
    {"gameName":"Pistons",      "statsName": "Detroit Pistons"},
    {"gameName":"Pacers",       "statsName": "Indiana Pacers"},
    {"gameName":"Bucks",        "statsName": "Milwaukee Bucks"},
    {"gameName":"Heat",         "statsName": "Miami Heat"},
    {"gameName":"Hawks",        "statsName": "Atlanta Hawks"},
    {"gameName":"Hornets",      "statsName": "Charlotte Hornets"},
    {"gameName":"Magic",        "statsName": "Orlando Magic"},
    {"gameName":"Wizards",      "statsName": "Washington Wizards"},
    {"gameName":"Timberwolves", "statsName": "Minnesota Timberwolves"},
    {"gameName":"Thunder",      "statsName": "Oklahoma City Thunder"},
    {"gameName":"Rockets",      "statsName": "Houston Rockets"},
    {"gameName":"Grizzlies",    "statsName": "Memphis Grizzlies"},
    {"gameName":"Spurs",        "statsName": "San Antonio Spurs"},
    {"gameName":"Pelicans",     "statsName": "New Orleans Pelicans"},
    {"gameName":"Mavericks",    "statsName": "Dallas Mavericks"},
    {"gameName":"Trail Blazers","statsName": "Portland Trail Blazers"},
    {"gameName":"Jazz",         "statsName": "Utah Jazz"},
    {"gameName":"Nuggets",         "statsName": "Denver Nuggets"}]
    for (let i = 0; i < onePlayer.length ; i++){
            for (let j = 0; j < games.length ; j++){
                if(onePlayer[i].team === games[j].statsName){
                    let player ={name:onePlayer[i].name,team:onePlayer[i].team,teamSearch:games[j].gameName}
                    playersComplete.push(player)
                } 
            }
    }
    return playersComplete
}
async function searchRivalTeamName(playersComplete){
    const gameLocal = Object.values(games)
    const gameLocalB = Object.values(gameLocal[0])
    const gameComplete = []
    for (let i = 0; i < playersComplete.length ; i++){
            for (let j = 0; j < gameLocalB.length ; j++){
                if(playersComplete[i].teamSearch === gameLocalB[j].awayName){
                    let player ={name:playersComplete[i].name,team:playersComplete[i].team,teamSearch:playersComplete[i].teamSearch,rival:gameLocalB[j].homeName}
                    gameComplete.push(player)
                }
                if(playersComplete[i].teamSearch === gameLocalB[j].homeName){
                    let player ={name:playersComplete[i].name,team:playersComplete[i].team,teamSearch:playersComplete[i].teamSearch,rival:gameLocalB[j].awayName}
                    gameComplete.push(player)
                }
            }
    }
    return gameComplete
}
